### ISSUE TITLE
ScrollTo Zero Causes List Loading Problems

### ISSUE THREAD

**Issue by LordHelmchen12** [aillieo/UnityDynamicScrollView#8]
When I scroll my List to 0 by ScrollToIndex often it happens (not all the time) that the list is now working properly anymore.

I am using ScrollEx, testes on lists between 200 and 3500 entries.

-Can only scroll down a few entries
-To where I scroll down, list seems to end there (scrollView is thinking list has only 1 page of entries?)
-Scrolling again to zero often fixes the problem
-can't tell when its hapening

Tested this in your demo project aswell:
Added a Button scrolling to Zero.
Created huge list. Scrolled up and down a bit. Pressed ScrollToZero.
Sometimes list not working properly anymore. 

I can't figure out on how to reproduce this all the time.
Any Ideas on that one?

![grafik](https://user-images.githubusercontent.com/2505595/119981710-38a59800-bfbe-11eb-89f2-dace638656b1.png)
(50.000 Entries, only first 17 visable while scrolling, should be max Page Size)

**Comment by aillieo** [comment]
Sorry for the inconvenience

In order to locate the problem, Id like to ask first if you are using the latest version of the code including the latest two commits  
[d0d055d](https://github.com/aillieo/UnityDynamicScrollView/commit/d0d055dbe49638954f4b25b8aa01dd37658144ba) and [03cb370](https://github.com/aillieo/UnityDynamicScrollView/commit/03cb370e5f0d9230e8d00415d9faeec861eb356e)

**Comment by LordHelmchen12** [comment]
Live Safer ! Thank you man!
<3

I missed one change of you here.
